const sqlite3 = require("sqlite3").verbose();
const db = new sqlite3.Database("pet_inventary.db");
const data = [
	{
		Name: "Gare",
		Age: 3,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/211x100.png/ff4444/ffffff",
	},
	{
		Name: "Birk",
		Age: 8,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/240x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Clarabelle",
		Age: 5,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/250x100.png/dddddd/000000",
	},
	{
		Name: "Hedvig",
		Age: 9,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/250x100.png/cc0000/ffffff",
	},
	{
		Name: "Bar",
		Age: 3,
		Gender: "Female",
		Type: "Cat",
		Adopted: false,
		Image: "http://dummyimage.com/158x100.png/ff4444/ffffff",
	},
	{
		Name: "Ekaterina",
		Age: 3,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/151x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Oralee",
		Age: 2,
		Gender: "Male",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/178x100.png/cc0000/ffffff",
	},
	{
		Name: "Beatrisa",
		Age: 10,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/202x100.png/ff4444/ffffff",
	},
	{
		Name: "Claiborne",
		Age: 9,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/213x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Dody",
		Age: 8,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/211x100.png/cc0000/ffffff",
	},
	{
		Name: "Taite",
		Age: 10,
		Gender: "Female",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/142x100.png/dddddd/000000",
	},
	{
		Name: "Rebeca",
		Age: 4,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/226x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Rheba",
		Age: 3,
		Gender: "Male",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/133x100.png/dddddd/000000",
	},
	{
		Name: "Arlie",
		Age: 4,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/224x100.png/cc0000/ffffff",
	},
	{
		Name: "Garrek",
		Age: 10,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/231x100.png/ff4444/ffffff",
	},
	{
		Name: "Humberto",
		Age: 1,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/173x100.png/dddddd/000000",
	},
	{
		Name: "Aubert",
		Age: 3,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/166x100.png/ff4444/ffffff",
	},
	{
		Name: "Latrena",
		Age: 5,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/107x100.png/dddddd/000000",
	},
	{
		Name: "Kissiah",
		Age: 2,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/101x100.png/dddddd/000000",
	},
	{
		Name: "Kalli",
		Age: 5,
		Gender: "Male",
		Type: "Cat",
		Adopted: false,
		Image: "http://dummyimage.com/181x100.png/cc0000/ffffff",
	},
	{
		Name: "Massimo",
		Age: 2,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/158x100.png/dddddd/000000",
	},
	{
		Name: "Janean",
		Age: 9,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/161x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Rhys",
		Age: 7,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/161x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Letti",
		Age: 1,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/244x100.png/cc0000/ffffff",
	},
	{
		Name: "Sukey",
		Age: 10,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/165x100.png/ff4444/ffffff",
	},
	{
		Name: "Silvana",
		Age: 7,
		Gender: "Male",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/113x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Harcourt",
		Age: 1,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/206x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Arch",
		Age: 6,
		Gender: "Male",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/216x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Blanch",
		Age: 2,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/141x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Benita",
		Age: 5,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/241x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Keefer",
		Age: 2,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/122x100.png/ff4444/ffffff",
	},
	{
		Name: "Gerta",
		Age: 2,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/141x100.png/ff4444/ffffff",
	},
	{
		Name: "Fabian",
		Age: 4,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/130x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Christin",
		Age: 1,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/113x100.png/dddddd/000000",
	},
	{
		Name: "Ariel",
		Age: 7,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/218x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Marinna",
		Age: 10,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/103x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Anet",
		Age: 6,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/116x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Burch",
		Age: 3,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/168x100.png/cc0000/ffffff",
	},
	{
		Name: "Lindsay",
		Age: 6,
		Gender: "Male",
		Type: "Cat",
		Adopted: false,
		Image: "http://dummyimage.com/196x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Robenia",
		Age: 10,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/124x100.png/ff4444/ffffff",
	},
	{
		Name: "Harriot",
		Age: 7,
		Gender: "Male",
		Type: "Cat",
		Adopted: false,
		Image: "http://dummyimage.com/233x100.png/cc0000/ffffff",
	},
	{
		Name: "Abe",
		Age: 2,
		Gender: "Female",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/156x100.png/cc0000/ffffff",
	},
	{
		Name: "Bridget",
		Age: 3,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/106x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Blithe",
		Age: 3,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/119x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Tabbitha",
		Age: 2,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Corty",
		Age: 2,
		Gender: "Female",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/126x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Miles",
		Age: 3,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/220x100.png/cc0000/ffffff",
	},
	{
		Name: "Harris",
		Age: 5,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/195x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Justine",
		Age: 4,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/242x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Zsa zsa",
		Age: 8,
		Gender: "Male",
		Type: "Cat",
		Adopted: false,
		Image: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Zonnya",
		Age: 10,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/250x100.png/ff4444/ffffff",
	},
	{
		Name: "Deane",
		Age: 10,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/138x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Leandra",
		Age: 9,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/130x100.png/ff4444/ffffff",
	},
	{
		Name: "Sherilyn",
		Age: 9,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/228x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Jerald",
		Age: 7,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/217x100.png/cc0000/ffffff",
	},
	{
		Name: "Daisey",
		Age: 5,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/119x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Dorolisa",
		Age: 4,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/176x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Joellen",
		Age: 1,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/145x100.png/ff4444/ffffff",
	},
	{
		Name: "Maggie",
		Age: 9,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/241x100.png/dddddd/000000",
	},
	{
		Name: "Grover",
		Age: 10,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/233x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Barnard",
		Age: 7,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/225x100.png/dddddd/000000",
	},
	{
		Name: "Celesta",
		Age: 1,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/200x100.png/ff4444/ffffff",
	},
	{
		Name: "Isac",
		Age: 2,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/144x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Stanislaw",
		Age: 6,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/221x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Skelly",
		Age: 8,
		Gender: "Female",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/181x100.png/ff4444/ffffff",
	},
	{
		Name: "Julian",
		Age: 10,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/122x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Urbano",
		Age: 10,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/240x100.png/ff4444/ffffff",
	},
	{
		Name: "Tammara",
		Age: 10,
		Gender: "Female",
		Type: "Cat",
		Adopted: false,
		Image: "http://dummyimage.com/142x100.png/dddddd/000000",
	},
	{
		Name: "Roman",
		Age: 9,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/112x100.png/ff4444/ffffff",
	},
	{
		Name: "Neile",
		Age: 10,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/108x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Gothart",
		Age: 4,
		Gender: "Female",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/165x100.png/cc0000/ffffff",
	},
	{
		Name: "Nanete",
		Age: 8,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Anetta",
		Age: 7,
		Gender: "Female",
		Type: "Cat",
		Adopted: false,
		Image: "http://dummyimage.com/137x100.png/cc0000/ffffff",
	},
	{
		Name: "Korrie",
		Age: 5,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/235x100.png/dddddd/000000",
	},
	{
		Name: "Egon",
		Age: 8,
		Gender: "Male",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/138x100.png/dddddd/000000",
	},
	{
		Name: "Karna",
		Age: 5,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/208x100.png/ff4444/ffffff",
	},
	{
		Name: "Jelene",
		Age: 8,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Jackie",
		Age: 3,
		Gender: "Male",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/168x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Vernice",
		Age: 7,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/214x100.png/dddddd/000000",
	},
	{
		Name: "Prent",
		Age: 4,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/224x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Rolland",
		Age: 10,
		Gender: "Male",
		Type: "DOG",
		Adopted: true,
		Image: "http://dummyimage.com/116x100.png/dddddd/000000",
	},
	{
		Name: "Eba",
		Age: 3,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/152x100.png/ff4444/ffffff",
	},
	{
		Name: "Geoff",
		Age: 7,
		Gender: "Male",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/239x100.png/cc0000/ffffff",
	},
	{
		Name: "Nickie",
		Age: 5,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/186x100.png/dddddd/000000",
	},
	{
		Name: "Terri",
		Age: 2,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/231x100.png/ff4444/ffffff",
	},
	{
		Name: "Ellswerth",
		Age: 4,
		Gender: "Male",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/131x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Sibyl",
		Age: 10,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/233x100.png/cc0000/ffffff",
	},
	{
		Name: "Donn",
		Age: 9,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/164x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Arnaldo",
		Age: 5,
		Gender: "Female",
		Type: "Cat",
		Adopted: false,
		Image: "http://dummyimage.com/125x100.png/ff4444/ffffff",
	},
	{
		Name: "Shelli",
		Age: 9,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/190x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Farlay",
		Age: 2,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/188x100.png/ff4444/ffffff",
	},
	{
		Name: "Shandee",
		Age: 3,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/140x100.png/ff4444/ffffff",
	},
	{
		Name: "Bunny",
		Age: 3,
		Gender: "Male",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/195x100.png/cc0000/ffffff",
	},
	{
		Name: "Charles",
		Age: 7,
		Gender: "Female",
		Type: "Cat",
		Adopted: false,
		Image: "http://dummyimage.com/181x100.png/ff4444/ffffff",
	},
	{
		Name: "Sadella",
		Age: 6,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/151x100.png/cc0000/ffffff",
	},
	{
		Name: "Christabel",
		Age: 3,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: false,
		Image: "http://dummyimage.com/157x100.png/cc0000/ffffff",
	},
	{
		Name: "Bryana",
		Age: 1,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/147x100.png/dddddd/000000",
	},
	{
		Name: "Lucita",
		Age: 4,
		Gender: "Female",
		Type: "Cat",
		Adopted: true,
		Image: "http://dummyimage.com/120x100.png/cc0000/ffffff",
	},
	{
		Name: "Judye",
		Age: 2,
		Gender: "Female",
		Type: "DOG",
		Adopted: false,
		Image: "http://dummyimage.com/249x100.png/5fa2dd/ffffff",
	},
	{
		Name: "Jonie",
		Age: 8,
		Gender: "Female",
		Type: "Rabbit",
		Adopted: true,
		Image: "http://dummyimage.com/210x100.png/dddddd/000000",
	},
];
db.serialize(function () {
	// try {
	// 	db.run("CREATE TABLE TO_ADOPT (id INTEGER , name VARCHAR,type VARCHAR)");
	// 	db.run(
	// 		"CREATE TABLE ADOPTED (id INTEGER , name VARCHAR,owner_name VARCHAR,email VARCHAR,date DATETIME)"
	// 	);
	// } catch (e) {}
	let counter = 0;
	data.forEach((pet) => {
		counter++;
		let petToAdopt = {
			id: counter,
			name: pet.Name,
			type: pet.Type,
		};
		let petData = Object.values(petToAdopt);
		if (!pet.Adopted) {
		console.log(petData);
			let query = "INSERT INTO TO_ADOPT(id,name,type) VALUES (?,?,?)";
			db.run(query, petData, (e) => {
				if (e) {
					return console.log(e.message);
				}
			});
		}
	});
});

db.close();
